export type Challenge = {
  id: number;
  word: string;
  tip: string;
  category: "Cotidiano" | "Esporte" | "Ciência";
};

export const WORDS: Challenge[] = [
  // 🏠 Cotidiano
  {
    id: 1,
    word: "CAFÉ",
    tip: "Bebida que muitos tomam pela manhã",
    category: "Cotidiano",
  },
  {
    id: 2,
    word: "CHAVE",
    tip: "Objeto usado para abrir portas",
    category: "Cotidiano",
  },
  {
    id: 3,
    word: "TRAVESSEIRO",
    tip: "Usado para apoiar a cabeça ao dormir",
    category: "Cotidiano",
  },
  {
    id: 4,
    word: "ESCOVA",
    tip: "Usada nos dentes ou nos cabelos",
    category: "Cotidiano",
  },
  {
    id: 5,
    word: "SOFA",
    tip: "Lugar confortável para assistir TV",
    category: "Cotidiano",
  },
  {
    id: 6,
    word: "GELADEIRA",
    tip: "Mantém os alimentos frios",
    category: "Cotidiano",
  },
  {
    id: 7,
    word: "CELULAR",
    tip: "Usado para mensagens, fotos e redes sociais",
    category: "Cotidiano",
  },
  {
    id: 8,
    word: "BOLSA",
    tip: "Acessório para carregar objetos pessoais",
    category: "Cotidiano",
  },
  {
    id: 9,
    word: "CHUVEIRO",
    tip: "Equipamento para tomar banho",
    category: "Cotidiano",
  },
  {
    id: 26,
    word: "JANELA",
    tip: "Abertura para ver o mundo lá fora",
    category: "Cotidiano",
  },
  {
    id: 27,
    word: "PORTA",
    tip: "Usada para entrar e sair de um lugar",
    category: "Cotidiano",
  },
  {
    id: 28,
    word: "LIVRO",
    tip: "Cheio de histórias e conhecimento",
    category: "Cotidiano",
  },
  {
    id: 29,
    word: "CADERNO",
    tip: "Para escrever e desenhar na escola",
    category: "Cotidiano",
  },
  {
    id: 30,
    word: "MESA",
    tip: "Onde fazemos refeições e atividades",
    category: "Cotidiano",
  },
  {
    id: 31,
    word: "CADEIRA",
    tip: "Para sentar e descansar",
    category: "Cotidiano",
  },
  {
    id: 32,
    word: "COPO",
    tip: "Usado para beber água e suco",
    category: "Cotidiano",
  },
  {
    id: 33,
    word: "PRATO",
    tip: "Onde colocamos a comida",
    category: "Cotidiano",
  },
  {
    id: 34,
    word: "GARFO",
    tip: "Usado para comer massas e carnes",
    category: "Cotidiano",
  },
  {
    id: 35,
    word: "COLHER",
    tip: "Usada para comer sopas e doces",
    category: "Cotidiano",
  },
  {
    id: 36,
    word: "FACA",
    tip: "Usada para cortar alimentos",
    category: "Cotidiano",
  },
  {
    id: 37,
    word: "TELEVISAO",
    tip: "Para assistir desenhos e filmes",
    category: "Cotidiano",
  },
  {
    id: 38,
    word: "RADIO",
    tip: "Para ouvir músicas e notícias",
    category: "Cotidiano",
  },
  {
    id: 39,
    word: "COMPUTADOR",
    tip: "Para jogar e aprender coisas novas",
    category: "Cotidiano",
  },
  {
    id: 40,
    word: "TECLADO",
    tip: "Usado para escrever no computador",
    category: "Cotidiano",
  },
  {
    id: 41,
    word: "MOUSE",
    tip: "Controla o cursor na tela do computador",
    category: "Cotidiano",
  },
  {
    id: 42,
    word: "LAMPADA",
    tip: "Ilumina os ambientes",
    category: "Cotidiano",
  },
  {
    id: 43,
    word: "VENTILADOR",
    tip: "Refresca o ar nos dias quentes",
    category: "Cotidiano",
  },
  {
    id: 44,
    word: "ARMARIO",
    tip: "Para guardar roupas e objetos",
    category: "Cotidiano",
  },
  {
    id: 45,
    word: "ESPELHO",
    tip: "Reflete nossa imagem",
    category: "Cotidiano",
  },
  { id: 46, word: "VASO", tip: "Para colocar flores", category: "Cotidiano" },
  {
    id: 47,
    word: "TAPETE",
    tip: "Enfeita o chão e aquece os pés",
    category: "Cotidiano",
  },
  {
    id: 48,
    word: "CORTINA",
    tip: "Controla a luz que entra pela janela",
    category: "Cotidiano",
  },
  {
    id: 49,
    word: "QUADRO",
    tip: "Enfeita a parede com imagens",
    category: "Cotidiano",
  },
  {
    id: 50,
    word: "ALMOFADA",
    tip: "Macia para apoiar a cabeça",
    category: "Cotidiano",
  },
  {
    id: 51,
    word: "BALDE",
    tip: "Para carregar água e outros líquidos",
    category: "Cotidiano",
  },
  {
    id: 52,
    word: "VASSOURA",
    tip: "Para limpar o chão",
    category: "Cotidiano",
  },
  {
    id: 53,
    word: "PANO",
    tip: "Usado para limpar superfícies",
    category: "Cotidiano",
  },
  { id: 54, word: "LIXO", tip: "O que jogamos fora", category: "Cotidiano" },
  {
    id: 201,
    word: "CHALEIRA",
    tip: "Usada para ferver água",
    category: "Cotidiano",
  },
  {
    id: 202,
    word: "XICARA",
    tip: "Para tomar chá ou café",
    category: "Cotidiano",
  },
  {
    id: 203,
    word: "BULE",
    tip: "Recipiente para servir chá ou café",
    category: "Cotidiano",
  },
  {
    id: 204,
    word: "AÇUCAREIRO",
    tip: "Onde guardamos o açúcar",
    category: "Cotidiano",
  },
  {
    id: 205,
    word: "GUARDANAPO",
    tip: "Usado para limpar a boca",
    category: "Cotidiano",
  },
  {
    id: 206,
    word: "JARRA",
    tip: "Para servir suco ou água",
    category: "Cotidiano",
  },
  {
    id: 207,
    word: "BANHEIRA",
    tip: "Para tomar banho relaxante",
    category: "Cotidiano",
  },
  {
    id: 208,
    word: "PIA",
    tip: "Onde lavamos as mãos e louça",
    category: "Cotidiano",
  },
  {
    id: 209,
    word: "TORNEIRA",
    tip: "De onde sai a água",
    category: "Cotidiano",
  },
  {
    id: 210,
    word: "ESPONJA",
    tip: "Usada para lavar louça",
    category: "Cotidiano",
  },
  {
    id: 211,
    word: "DETERGENTE",
    tip: "Usado para limpar",
    category: "Cotidiano",
  },
  {
    id: 212,
    word: "PANELA",
    tip: "Para cozinhar alimentos",
    category: "Cotidiano",
  },
  {
    id: 213,
    word: "FRIGIDEIRA",
    tip: "Para fritar alimentos",
    category: "Cotidiano",
  },
  {
    id: 214,
    word: "FORNO",
    tip: "Para assar alimentos",
    category: "Cotidiano",
  },
  {
    id: 215,
    word: "MICROONDAS",
    tip: "Para aquecer alimentos rápido",
    category: "Cotidiano",
  },
  {
    id: 216,
    word: "LIQUIDIFICADOR",
    tip: "Para fazer sucos e vitaminas",
    category: "Cotidiano",
  },
  {
    id: 217,
    word: "BATEDEIRA",
    tip: "Para fazer bolos e massas",
    category: "Cotidiano",
  },
  {
    id: 218,
    word: "GELADEIRA",
    tip: "Para guardar alimentos frescos",
    category: "Cotidiano",
  },
  {
    id: 219,
    word: "FREEZER",
    tip: "Para congelar alimentos",
    category: "Cotidiano",
  },
  {
    id: 220,
    word: "LAVANDERIA",
    tip: "Onde lavamos a roupa",
    category: "Cotidiano",
  },
  { id: 221, word: "MAQUINA", tip: "Lava a roupa", category: "Cotidiano" },
  {
    id: 222,
    word: "VARAL",
    tip: "Onde secamos a roupa",
    category: "Cotidiano",
  },
  {
    id: 223,
    word: "PREGADOR",
    tip: "Para prender a roupa no varal",
    category: "Cotidiano",
  },
  { id: 224, word: "FERRO", tip: "Para passar a roupa", category: "Cotidiano" },
  {
    id: 225,
    word: "TABUA",
    tip: "Onde passamos a roupa",
    category: "Cotidiano",
  },
  { id: 226, word: "QUARTO", tip: "Onde dormimos", category: "Cotidiano" },
  { id: 227, word: "SALA", tip: "Onde assistimos TV", category: "Cotidiano" },
  { id: 228, word: "COZINHA", tip: "Onde cozinhamos", category: "Cotidiano" },
  {
    id: 229,
    word: "BANHEIRO",
    tip: "Onde tomamos banho",
    category: "Cotidiano",
  },

  // 🏅 Esporte
  {
    id: 10,
    word: "FUTEBOL",
    tip: "Esporte mais popular no Brasil",
    category: "Esporte",
  },
  {
    id: 11,
    word: "BASQUETE",
    tip: "Esporte com bola e cestas elevadas",
    category: "Esporte",
  },
  {
    id: 12,
    word: "CORRIDA",
    tip: "Atividade física de velocidade",
    category: "Esporte",
  },
  {
    id: 13,
    word: "NATAÇÃO",
    tip: "Modalidade praticada em piscinas",
    category: "Esporte",
  },
  {
    id: 14,
    word: "JUDO",
    tip: "Arte marcial de agarrões e quedas",
    category: "Esporte",
  },
  {
    id: 15,
    word: "GOL",
    tip: "Principal objetivo do jogo de futebol",
    category: "Esporte",
  },
  {
    id: 16,
    word: "BOXE",
    tip: "Esporte de combate com luvas",
    category: "Esporte",
  },
  {
    id: 17,
    word: "CICLISMO",
    tip: "Esporte praticado com bicicleta",
    category: "Esporte",
  },
  {
    id: 55,
    word: "PISCINA",
    tip: "Onde nadamos e brincamos na água",
    category: "Esporte",
  },
  {
    id: 56,
    word: "BOLA",
    tip: "Usada em muitos esportes",
    category: "Esporte",
  },
  { id: 57, word: "REDE", tip: "Usada no vôlei e tênis", category: "Esporte" },
  { id: 58, word: "CAMPO", tip: "Onde jogamos futebol", category: "Esporte" },
  {
    id: 59,
    word: "PISTA",
    tip: "Onde corremos e andamos de skate",
    category: "Esporte",
  },
  {
    id: 60,
    word: "CAPACETE",
    tip: "Protege a cabeça em esportes radicais",
    category: "Esporte",
  },
  {
    id: 61,
    word: "JOELHEIRA",
    tip: "Protege os joelhos em esportes",
    category: "Esporte",
  },
  {
    id: 62,
    word: "COTOVELEIRA",
    tip: "Protege os cotovelos em esportes",
    category: "Esporte",
  },
  {
    id: 63,
    word: "UNIFORME",
    tip: "Roupa usada pelos atletas",
    category: "Esporte",
  },
  {
    id: 64,
    word: "MEDALHA",
    tip: "Prêmio para os vencedores",
    category: "Esporte",
  },
  { id: 65, word: "TROFEU", tip: "Prêmio para o campeão", category: "Esporte" },
  {
    id: 66,
    word: "JUIZ",
    tip: "Garante que as regras sejam cumpridas",
    category: "Esporte",
  },
  {
    id: 67,
    word: "TORCIDA",
    tip: "Pessoas que apoiam um time",
    category: "Esporte",
  },
  {
    id: 68,
    word: "ESTADIO",
    tip: "Onde acontecem os jogos",
    category: "Esporte",
  },
  {
    id: 69,
    word: "GINASIO",
    tip: "Local para praticar esportes indoor",
    category: "Esporte",
  },
  { id: 70, word: "TREINADOR", tip: "Orienta os atletas", category: "Esporte" },
  { id: 71, word: "EQUIPE", tip: "Grupo de jogadores", category: "Esporte" },
  {
    id: 72,
    word: "PONTO",
    tip: "Unidade de contagem no jogo",
    category: "Esporte",
  },
  {
    id: 73,
    word: "FAIXA",
    tip: "Usada em artes marciais",
    category: "Esporte",
  },
  {
    id: 74,
    word: "TATAME",
    tip: "Onde se pratica judô e karatê",
    category: "Esporte",
  },
  {
    id: 75,
    word: "RAQUETE",
    tip: "Usada no tênis e badminton",
    category: "Esporte",
  },
  {
    id: 76,
    word: "PETECA",
    tip: "Usada no jogo de peteca",
    category: "Esporte",
  },
  {
    id: 77,
    word: "SKATEBOARD",
    tip: "Prancha para andar de skate",
    category: "Esporte",
  },
  { id: 78, word: "BICICLETA", tip: "Usada no ciclismo", category: "Esporte" },
  {
    id: 79,
    word: "NADADEIRA",
    tip: "Ajuda a nadar mais rápido",
    category: "Esporte",
  },
  { id: 80, word: "PRANCHA", tip: "Usada no surf", category: "Esporte" },
  { id: 81, word: "REMO", tip: "Usado para remar", category: "Esporte" },
  { id: 82, word: "CANOA", tip: "Embarcação para remar", category: "Esporte" },
  {
    id: 83,
    word: "CAIAQUE",
    tip: "Embarcação individual para remar",
    category: "Esporte",
  },
  { id: 230, word: "APITO", tip: "Usado pelo juiz", category: "Esporte" },
  { id: 231, word: "CRONOMETRO", tip: "Mede o tempo", category: "Esporte" },
  { id: 232, word: "PLACA", tip: "Indica o placar", category: "Esporte" },
  {
    id: 233,
    word: "BANCO",
    tip: "Onde ficam os reservas",
    category: "Esporte",
  },
  { id: 234, word: "AQUECIMENTO", tip: "Prepara o corpo", category: "Esporte" },
  {
    id: 235,
    word: "ALONGAMENTO",
    tip: "Estica os músculos",
    category: "Esporte",
  },
  { id: 236, word: "COLETE", tip: "Usado em treinos", category: "Esporte" },
  { id: 237, word: "CONE", tip: "Marca o campo", category: "Esporte" },
  { id: 238, word: "BARREIRA", tip: "Para saltar", category: "Esporte" },
  { id: 239, word: "ARGOLA", tip: "Usada na ginástica", category: "Esporte" },
  { id: 240, word: "CAVALO", tip: "Usado no hipismo", category: "Esporte" },
  { id: 241, word: "ESPADA", tip: "Usada na esgrima", category: "Esporte" },
  { id: 242, word: "FLECHA", tip: "Lançada com o arco", category: "Esporte" },
  { id: 243, word: "ALVO", tip: "Onde se mira", category: "Esporte" },
  {
    id: 244,
    word: "REVEZAMENTO",
    tip: "Corrida em equipe",
    category: "Esporte",
  },
  { id: 245, word: "MARATONA", tip: "Corrida longa", category: "Esporte" },
  { id: 246, word: "OBSTACULO", tip: "Para superar", category: "Esporte" },
  { id: 247, word: "SALTO", tip: "Para pular", category: "Esporte" },
  { id: 248, word: "LANÇAMENTO", tip: "Para arremessar", category: "Esporte" },
  { id: 249, word: "PESO", tip: "Para levantar", category: "Esporte" },
  { id: 250, word: "DISCO", tip: "Para arremessar", category: "Esporte" },
  { id: 251, word: "DARDO", tip: "Para lançar", category: "Esporte" },
  { id: 252, word: "MARTELO", tip: "Para girar e lançar", category: "Esporte" },
  {
    id: 253,
    word: "GINASTICA",
    tip: "Exercícios de força",
    category: "Esporte",
  },
  {
    id: 254,
    word: "AEROBICA",
    tip: "Exercícios com música",
    category: "Esporte",
  },
  {
    id: 255,
    word: "MUSCULAÇÃO",
    tip: "Exercícios com peso",
    category: "Esporte",
  },
  {
    id: 256,
    word: "YOGA",
    tip: "Exercícios de relaxamento",
    category: "Esporte",
  },
  {
    id: 257,
    word: "PILATES",
    tip: "Exercícios de postura",
    category: "Esporte",
  },
  { id: 258, word: "DANÇA", tip: "Movimentos com ritmo", category: "Esporte" },
  {
    id: 259,
    word: "CAPOEIRA",
    tip: "Arte marcial brasileira",
    category: "Esporte",
  },

  // 🧪 Ciência
  {
    id: 18,
    word: "ATOMO",
    tip: "Unidade fundamental da matéria",
    category: "Ciência",
  },
  {
    id: 19,
    word: "CELULA",
    tip: "Unidade básica dos seres vivos",
    category: "Ciência",
  },
  {
    id: 20,
    word: "GRAVIDADE",
    tip: "Nos mantém com os pés no chão",
    category: "Ciência",
  },
  {
    id: 21,
    word: "GENETICA",
    tip: "Estuda a hereditariedade",
    category: "Ciência",
  },
  {
    id: 22,
    word: "PLANETA",
    tip: "Corpo celeste que orbita uma estrela",
    category: "Ciência",
  },
  {
    id: 23,
    word: "ENERGIA",
    tip: "Essencial para movimento e calor",
    category: "Ciência",
  },
  {
    id: 24,
    word: "NEURONIO",
    tip: "Célula do sistema nervoso",
    category: "Ciência",
  },
  {
    id: 25,
    word: "EVOLUCAO",
    tip: "Processo de mudança nas espécies",
    category: "Ciência",
  },
  {
    id: 84,
    word: "MICROSCOPIO",
    tip: "Aparelho para ver coisas muito pequenas",
    category: "Ciência",
  },
  {
    id: 85,
    word: "TELESCOPIO",
    tip: "Aparelho para ver estrelas e planetas",
    category: "Ciência",
  },
  { id: 86, word: "IMÃ", tip: "Atrai objetos de metal", category: "Ciência" },
  {
    id: 87,
    word: "LUPA",
    tip: "Aumenta o tamanho das coisas",
    category: "Ciência",
  },
  {
    id: 88,
    word: "BALANÇA",
    tip: "Mede o peso das coisas",
    category: "Ciência",
  },
  {
    id: 89,
    word: "TERMOMETRO",
    tip: "Mede a temperatura",
    category: "Ciência",
  },
  { id: 90, word: "MAPA", tip: "Representação da Terra", category: "Ciência" },
  { id: 91, word: "BUSSOLA", tip: "Mostra a direção", category: "Ciência" },
  {
    id: 92,
    word: "ROBOT",
    tip: "Máquina que faz tarefas",
    category: "Ciência",
  },
  {
    id: 93,
    word: "DNA",
    tip: "Guarda informações dos seres vivos",
    category: "Ciência",
  },
  { id: 94, word: "OSSOS", tip: "Formam o esqueleto", category: "Ciência" },
  {
    id: 95,
    word: "MUSCULOS",
    tip: "Permitem o movimento",
    category: "Ciência",
  },
  { id: 96, word: "CORACAO", tip: "Bombeia o sangue", category: "Ciência" },
  { id: 97, word: "CEREBRO", tip: "Controla o corpo", category: "Ciência" },
  { id: 98, word: "PULMAO", tip: "Respira o ar", category: "Ciência" },
  {
    id: 99,
    word: "SANGUE",
    tip: "Líquido que corre nas veias",
    category: "Ciência",
  },
  {
    id: 100,
    word: "BACTERIA",
    tip: "Ser vivo muito pequeno",
    category: "Ciência",
  },
  { id: 101, word: "VIRUS", tip: "Causa doenças", category: "Ciência" },
  {
    id: 102,
    word: "VACINA",
    tip: "Protege contra doenças",
    category: "Ciência",
  },
  { id: 103, word: "REMEDIO", tip: "Cura doenças", category: "Ciência" },
  {
    id: 104,
    word: "PLANETA",
    tip: "Terra, Marte, Júpiter...",
    category: "Ciência",
  },
  {
    id: 105,
    word: "GALAXIA",
    tip: "Conjunto de estrelas",
    category: "Ciência",
  },
  { id: 106, word: "ASTRONAUTA", tip: "Viaja no espaço", category: "Ciência" },
  { id: 107, word: "FOGUETE", tip: "Leva ao espaço", category: "Ciência" },
  {
    id: 108,
    word: "SATELITE",
    tip: "Gira em volta da Terra",
    category: "Ciência",
  },
  {
    id: 109,
    word: "LAVA",
    tip: "Rocha derretida do vulcão",
    category: "Ciência",
  },
  {
    id: 110,
    word: "MINERAL",
    tip: "Encontrado nas rochas",
    category: "Ciência",
  },
  {
    id: 111,
    word: "ARCO-IRIS",
    tip: "Cores no céu após a chuva",
    category: "Ciência",
  },
  { id: 112, word: "NUVEM", tip: "Feita de água no céu", category: "Ciência" },
  {
    id: 113,
    word: "TROVAO",
    tip: "Barulho forte na tempestade",
    category: "Ciência",
  },
  {
    id: 114,
    word: "RAIO",
    tip: "Luz forte na tempestade",
    category: "Ciência",
  },
  {
    id: 115,
    word: "FLORESTA",
    tip: "Cheia de árvores e animais",
    category: "Ciência",
  },
  { id: 116, word: "RIO", tip: "Água que corre", category: "Ciência" },
  {
    id: 117,
    word: "MAR",
    tip: "Grande massa de água salgada",
    category: "Ciência",
  },
  { id: 118, word: "PEIXE", tip: "Vive na água", category: "Ciência" },
  { id: 119, word: "AVE", tip: "Animal que voa", category: "Ciência" },
  { id: 120, word: "MAMIFERO", tip: "Animal que mama", category: "Ciência" },
  { id: 121, word: "REPTIL", tip: "Animal que rasteja", category: "Ciência" },
  {
    id: 122,
    word: "ANFIBIO",
    tip: "Vive na água e na terra",
    category: "Ciência",
  },
  {
    id: 123,
    word: "INVERTEBRADO",
    tip: "Animal sem ossos",
    category: "Ciência",
  },
  { id: 124, word: "VERTEBRADO", tip: "Animal com ossos", category: "Ciência" },
  {
    id: 125,
    word: "FOTOSSINTESE",
    tip: "Como as plantas fazem comida",
    category: "Ciência",
  },
  {
    id: 126,
    word: "ECOSSISTEMA",
    tip: "Onde seres vivos interagem",
    category: "Ciência",
  },
  {
    id: 127,
    word: "POLUIÇÃO",
    tip: "Sujeira no ambiente",
    category: "Ciência",
  },
  {
    id: 128,
    word: "RECICLAGEM",
    tip: "Transformar lixo em novo",
    category: "Ciência",
  },
  {
    id: 129,
    word: "ENERGIA",
    tip: "Faz as coisas funcionarem",
    category: "Ciência",
  },
  {
    id: 130,
    word: "ELETRICIDADE",
    tip: "Energia que acende a luz",
    category: "Ciência",
  },
  { id: 131, word: "MAGNETISMO", tip: "Força do imã", category: "Ciência" },
  { id: 132, word: "SOM", tip: "O que ouvimos", category: "Ciência" },
  { id: 133, word: "LUZ", tip: "O que vemos", category: "Ciência" },
  { id: 134, word: "CALOR", tip: "O que sentimos quente", category: "Ciência" },
  {
    id: 135,
    word: "MATERIA",
    tip: "Do que as coisas são feitas",
    category: "Ciência",
  },
  {
    id: 136,
    word: "ATOMO",
    tip: "Pequena parte da matéria",
    category: "Ciência",
  },
  { id: 137, word: "MOLECULA", tip: "Grupo de átomos", category: "Ciência" },
  { id: 138, word: "REACAO", tip: "Mudança na matéria", category: "Ciência" },
  {
    id: 139,
    word: "EXPERIMENTO",
    tip: "Teste para aprender",
    category: "Ciência",
  },
  {
    id: 140,
    word: "CIENTISTA",
    tip: "Quem faz experimentos",
    category: "Ciência",
  },
  { id: 141, word: "TEORIA", tip: "Explicação para algo", category: "Ciência" },
  { id: 142, word: "LEI", tip: "Regra da natureza", category: "Ciência" },
  {
    id: 143,
    word: "EVOLUCAO",
    tip: "Mudança nos seres vivos",
    category: "Ciência",
  },
  {
    id: 144,
    word: "ADAPTACAO",
    tip: "Como se ajustam ao ambiente",
    category: "Ciência",
  },
  {
    id: 145,
    word: "HEREDITARIEDADE",
    tip: "O que passa dos pais",
    category: "Ciência",
  },
  { id: 146, word: "GENE", tip: "Parte do DNA", category: "Ciência" },
  {
    id: 147,
    word: "CELULA",
    tip: "Pequena parte do ser vivo",
    category: "Ciência",
  },
  { id: 148, word: "TECIDO", tip: "Grupo de células", category: "Ciência" },
  { id: 149, word: "ORGAO", tip: "Parte do corpo", category: "Ciência" },
  { id: 150, word: "SISTEMA", tip: "Grupo de órgãos", category: "Ciência" },
  { id: 151, word: "ORGANISMO", tip: "Ser vivo completo", category: "Ciência" },
  {
    id: 152,
    word: "ESPECIE",
    tip: "Grupo de seres iguais",
    category: "Ciência",
  },
  {
    id: 153,
    word: "POPULACAO",
    tip: "Grupo de seres da mesma espécie",
    category: "Ciência",
  },
  {
    id: 154,
    word: "COMUNIDADE",
    tip: "Grupo de seres diferentes",
    category: "Ciência",
  },
  {
    id: 155,
    word: "BIOSFERA",
    tip: "Onde tem vida na Terra",
    category: "Ciência",
  },
  { id: 156, word: "CLIMA", tip: "Como é o tempo", category: "Ciência" },
  {
    id: 157,
    word: "TEMPERATURA",
    tip: "Quão quente ou frio",
    category: "Ciência",
  },
  { id: 158, word: "PRESSAO", tip: "Força do ar", category: "Ciência" },
  { id: 159, word: "UMIDADE", tip: "Quanta água no ar", category: "Ciência" },
  { id: 160, word: "VENTO", tip: "Ar em movimento", category: "Ciência" },
  { id: 161, word: "CHUVA", tip: "Água que cai do céu", category: "Ciência" },
  { id: 162, word: "NEVE", tip: "Água congelada que cai", category: "Ciência" },
  {
    id: 163,
    word: "GRANIZO",
    tip: "Pedras de gelo que caem",
    category: "Ciência",
  },
  { id: 164, word: "RELAMPAGO", tip: "Luz na tempestade", category: "Ciência" },
  {
    id: 165,
    word: "TROVAO",
    tip: "Barulho na tempestade",
    category: "Ciência",
  },
  {
    id: 166,
    word: "ARCO-IRIS",
    tip: "Cores após a chuva",
    category: "Ciência",
  },
  { id: 167, word: "NUVEM", tip: "Feita de água no céu", category: "Ciência" },
  { id: 168, word: "SOL", tip: "Estrela que ilumina", category: "Ciência" },
  { id: 169, word: "LUA", tip: "Gira em volta da Terra", category: "Ciência" },
  { id: 170, word: "ESTRELA", tip: "Brilha no céu", category: "Ciência" },
  {
    id: 171,
    word: "PLANETA",
    tip: "Gira em volta do Sol",
    category: "Ciência",
  },
  { id: 172, word: "GALAXIA", tip: "Grupo de estrelas", category: "Ciência" },
  { id: 173, word: "UNIVERSO", tip: "Tudo que existe", category: "Ciência" },
  { id: 174, word: "TEMPO", tip: "Como as coisas mudam", category: "Ciência" },
  {
    id: 175,
    word: "ESPAÇO",
    tip: "Onde estão os planetas",
    category: "Ciência",
  },
  {
    id: 176,
    word: "GRAVIDADE",
    tip: "Puxa as coisas para baixo",
    category: "Ciência",
  },
  {
    id: 177,
    word: "MOVIMENTO",
    tip: "Quando algo muda de lugar",
    category: "Ciência",
  },
  { id: 178, word: "FORÇA", tip: "Empurra ou puxa algo", category: "Ciência" },
  {
    id: 179,
    word: "ENERGIA",
    tip: "Faz as coisas se moverem",
    category: "Ciência",
  },
  {
    id: 180,
    word: "TRABALHO",
    tip: "Usar energia para fazer algo",
    category: "Ciência",
  },
  {
    id: 181,
    word: "MAQUINA",
    tip: "Ajuda a fazer trabalho",
    category: "Ciência",
  },
  {
    id: 182,
    word: "FERRAMENTA",
    tip: "Usada para construir",
    category: "Ciência",
  },
  {
    id: 183,
    word: "TECNOLOGIA",
    tip: "Uso da ciência para criar",
    category: "Ciência",
  },
  { id: 184, word: "INVENÇÃO", tip: "Algo novo criado", category: "Ciência" },
  { id: 185, word: "DESCOBERTA", tip: "Algo encontrado", category: "Ciência" },
  {
    id: 186,
    word: "PESQUISA",
    tip: "Buscar conhecimento",
    category: "Ciência",
  },
  { id: 187, word: "ESTUDO", tip: "Aprender sobre algo", category: "Ciência" },
  { id: 188, word: "CONHECIMENTO", tip: "O que sabemos", category: "Ciência" },
  {
    id: 189,
    word: "SABEDORIA",
    tip: "Usar o conhecimento bem",
    category: "Ciência",
  },
  { id: 190, word: "VERDADE", tip: "O que é real", category: "Ciência" },
  { id: 191, word: "MENTIRA", tip: "O que não é real", category: "Ciência" },
  { id: 192, word: "CERTO", tip: "O que é correto", category: "Ciência" },
  { id: 193, word: "ERRADO", tip: "O que não é correto", category: "Ciência" },
  { id: 194, word: "BOM", tip: "O que é positivo", category: "Ciência" },
  { id: 195, word: "MAU", tip: "O que é negativo", category: "Ciência" },
  {
    id: 196,
    word: "JUSTO",
    tip: "O que é igual para todos",
    category: "Ciência",
  },
  { id: 197, word: "INJUSTO", tip: "O que não é igual", category: "Ciência" },
  { id: 198, word: "PAZ", tip: "Sem guerra", category: "Ciência" },
  { id: 199, word: "GUERRA", tip: "Com conflito", category: "Ciência" },
  { id: 200, word: "AMOR", tip: "Sentimento bom", category: "Ciência" },
  { id: 260, word: "PLANETA", tip: "Terra, Marte...", category: "Ciência" },
  { id: 261, word: "ESTRELA", tip: "Sol, Sirius...", category: "Ciência" },
  { id: 262, word: "SATELITE", tip: "Lua...", category: "Ciência" },
  { id: 263, word: "COMETA", tip: "Halley...", category: "Ciência" },
  { id: 264, word: "ASTEROIDE", tip: "Ceres...", category: "Ciência" },
  { id: 265, word: "METEORO", tip: "Estrela cadente...", category: "Ciência" },
  { id: 266, word: "CONSTELAÇÃO", tip: "Órion...", category: "Ciência" },
  { id: 267, word: "GALAXIA", tip: "Via Láctea...", category: "Ciência" },
  { id: 268, word: "UNIVERSO", tip: "Tudo que existe...", category: "Ciência" },
  { id: 269, word: "BURACO", tip: "Negro...", category: "Ciência" },
  { id: 270, word: "MATERIA", tip: "Escura...", category: "Ciência" },
  { id: 271, word: "ENERGIA", tip: "Nuclear...", category: "Ciência" },
  { id: 272, word: "RADIOATIVIDADE", tip: "Urânio...", category: "Ciência" },
  { id: 273, word: "FISSÃO", tip: "Atômica...", category: "Ciência" },
  { id: 274, word: "FUSÃO", tip: "Nuclear...", category: "Ciência" },
  { id: 275, word: "REATOR", tip: "Nuclear...", category: "Ciência" },
  { id: 276, word: "ATOMO", tip: "Hidrogênio...", category: "Ciência" },
  { id: 277, word: "MOLECULA", tip: "Água...", category: "Ciência" },
  { id: 278, word: "ELEMENTO", tip: "Químico...", category: "Ciência" },
  { id: 279, word: "TABELA", tip: "Periódica...", category: "Ciência" },
  { id: 280, word: "ACIDO", tip: "Cítrico...", category: "Ciência" },
  { id: 281, word: "BASE", tip: "Soda cáustica...", category: "Ciência" },
  { id: 282, word: "SAL", tip: "De cozinha...", category: "Ciência" },
  { id: 283, word: "AGUA", tip: "H2O...", category: "Ciência" },
  { id: 284, word: "OXIGENIO", tip: "O2...", category: "Ciência" },
  { id: 285, word: "CARBONO", tip: "C...", category: "Ciência" },
  { id: 286, word: "NITROGENIO", tip: "N...", category: "Ciência" },
  { id: 287, word: "FERRO", tip: "Fe...", category: "Ciência" },
  { id: 288, word: "OURO", tip: "Au...", category: "Ciência" },
  { id: 289, word: "PRATA", tip: "Ag...", category: "Ciência" },
  { id: 290, word: "COBRE", tip: "Cu...", category: "Ciência" },
  { id: 291, word: "ALUMINIO", tip: "Al...", category: "Ciência" },
  { id: 292, word: "ENXOFRE", tip: "S...", category: "Ciência" },
  { id: 293, word: "FOSFORO", tip: "P...", category: "Ciência" },
  { id: 294, word: "CALCIO", tip: "Ca...", category: "Ciência" },
  { id: 295, word: "SODIO", tip: "Na...", category: "Ciência" },
  { id: 296, word: "POTASSIO", tip: "K...", category: "Ciência" },
  { id: 297, word: "MAGNESIO", tip: "Mg...", category: "Ciência" },
  { id: 298, word: "ZINCO", tip: "Zn...", category: "Ciência" },
  { id: 299, word: "MERCURIO", tip: "Hg...", category: "Ciência" },
  { id: 300, word: "CHUMBO", tip: "Pb...", category: "Ciência" },
];
